import type { Metadata } from "next";
import SplashScreen from "@/components/ui/splash-screen";
import ThemeProvider from "@/components/theme-provider";
import { inter, jetBrainsMono } from "@/components/ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${jetBrainsMono.variable}`}>
      <body className="antialiased min-h-full flex flex-col">
        {/* <SplashScreen /> */}
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
