import type { Metadata } from "next";
import { Inter, DM_Sans } from 'next/font/google';
import SplashScreen from "@/components/ui/splash-screen";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${inter.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className={`min-h-full flex flex-col`}>
        <SplashScreen />
        {children}
      </body>
    </html>
  );
}
