/**
 * Response shapes from the DevConnect Portal's public API.
 *
 * These mirror what the portal actually returns — they are not our preferences.
 * Anything the portal documents as nullable is nullable here, so the compiler
 * forces every consumer to handle the empty case instead of discovering it in
 * production.
 *
 * Source of truth: docs/portal-api.md.
 */

export type PortalOfficer = {
  id: string;
  /** The position, e.g. "President". Named `title` by the portal, `role` in our UI. */
  title: string;
  term_year: number | null;
  display_order: number;
  name: string;
  photo_url: string | null;
  bio: string | null;
};

/** The five categories the events UI has badge colours for. */
export const EVENT_CATEGORIES = ['hackaton', 'workshop', 'seminar', 'community', 'career'] as const;
export type PortalEventCategory = (typeof EVENT_CATEGORIES)[number];

export type PortalEvent = {
  id: string;
  /**
   * The event's readable URL segment, generated by the portal from the title,
   * unique, and frozen once set so a shared link keeps working.
   *
   * `null` for events created before the portal added slugs, which is why the
   * `id` route has to keep working (EVENTS-04).
   */
  slug: string | null;
  /**
   * Shorter links for the same event. Slugs come from titles and titles are
   * long; rather than change a slug and break what has been shared, an officer
   * adds an alias. The portal promises an array, never null.
   */
  slug_aliases: string[];
  title: string;
  description: string | null;
  location: string;
  /**
   * Sets the badge colour. `hackaton` is misspelled on purpose, on both sides:
   * the badge colours key on that exact string.
   */
  category: PortalEventCategory;
  /**
   * ISO 8601 in UTC, or `null` for an event whose date is still to be
   * announced ("TBA"). The portal guarantees start and end are both set or both
   * null.
   */
  start_date: string | null;
  end_date: string | null;
  cover_image_url: string | null;
};

/** The five places on the landing page an image can go (CMS-04). */
export const LANDING_SLOTS = ['hero-desktop', 'hero-mobile', 'who-we-are-carousel', 'what-we-do', 'bottom'] as const;
export type LandingSlot = (typeof LANDING_SLOTS)[number];

export type PortalLandingImage = {
  id: string;
  slot: LandingSlot;
  /** Always the portal's own Supabase storage; the portal omits anything else. */
  image_url: string;
  /** Never empty: the portal's database rejects an image without it. */
  alt: string;
  /** Caption; only the `what-we-do` cards show one. */
  label: string | null;
  display_order: number;
};

export type PortalLanding = {
  officers: PortalOfficer[];
  events: PortalEvent[];
  /** `[]` when the portal could not load its images; the rest of the payload still arrives. */
  images: PortalLandingImage[];
  generated_at: string;
};
